[package]
name = "pwmp-client"
version = "2.0.3"
edition = "2021"
authors = ["Fábián Varga <23280129+br0kenpixel@users.noreply.github.com>"]
description = "The PixelWeather Messaging Protocol client."
rust-version = "1.84"
homepage = "https://github.com/PixelWeatherProject"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/PixelWeatherProject/pwmp-client"

[dependencies]
thiserror = "2.0.11"
pwmp-msg = { path = "/home/br0kenpixel/Documents/C Projects/Rust/pwmp-new-stack/pwmp-msg" }
